language: erlang
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - R16B
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout v0.11.2 && make && cd ..
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test --no-start"
